export const volunteeringQuotes = [
  "Volunteers do not necessarily have the time; they just have the heart.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "Service to others is the rent you pay for your room here on earth.",
  "You make a living by what you get. You make a life by what you give.",
  "Volunteerism is the voice of the people put into action.",
  "Act as if what you do makes a difference. It does.",
  "No act of kindness, no matter how small, is ever wasted.",
  "We rise by lifting others.",
  "The meaning of life is to find your gift. The purpose of life is to give it away.",
  "Volunteering is an act of heroism on a grand scale.",
  "The unselfish effort to bring cheer to others will be the beginning of a happier life for ourselves.",
  "Alone we can do so little; together we can do so much.",
  "If you want to touch the past, touch a rock. If you want to touch the present, touch a flower. If you want to touch the future, touch a life.",
  "What we have done for ourselves alone dies with us; what we have done for others and the world remains and is immortal.",
  "Volunteers are the only human beings on the face of the earth who reflect this nation's compassion, unselfish caring, patience, and just plain loving one another.",
  "Everybody can be great. Because anybody can serve.",
  "Life's most persistent and urgent question is, 'What are you doing for others?'",
  "The smallest act of kindness is worth more than the grandest intention.",
  "To give without any reward, or any notice, has a special quality of its own.",
  "Only a life lived for others is a life worthwhile.",
  "Kindness is the language which the deaf can hear and the blind can see.",
  "Helping one person might not change the whole world, but it could change the world for one person.",
  "Start where you are. Use what you have. Do what you can.",
  "Volunteering is the ultimate exercise in democracy.",
  "It’s easy to make a buck. It’s a lot tougher to make a difference.",
  "The best antidote I have found is to do something for someone else.",
  "Unless someone like you cares a whole awful lot, nothing is going to get better. It’s not.",
  "Service is the very purpose of life. It is the rent we pay for living on the planet.",
  "There is no higher religion than human service. To work for the common good is the greatest creed.",
  "I slept and dreamt that life was joy. I awoke and saw that life was service. I acted and behold, service was joy.",
  "Your life is your message to the world. Make sure it’s inspiring.",
  "Doing nothing for others is the undoing of ourselves.",
  "The heart of a volunteer is not measured in size, but by the depth of the commitment to make a difference in the lives of others.",
  "Volunteers are paid in six figures... S-M-I-L-E-S.",
  "Those who can, do. Those who can do more, volunteer.",
  "Don’t ever underestimate the importance of what you are doing. History is changed by those who show up.",
  "Good actions give strength to ourselves and inspire good actions in others.",
  "The simplest acts of kindness are by far more powerful then a thousand heads bowing in prayer.",
  "Wherever there is a human being, there is an opportunity for a kindness.",
  "Be the change that you wish to see in the world.",
  "A candle loses nothing by lighting another candle.",
  "As you grow older, you will discover that you have two hands — one for helping yourself, the other for helping others.",
  "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.",
  "We make a living by what we get, but we make a life by what we give.",
  "Happiness is not something ready made. It comes from your own actions.",
  "The purpose of human life is to serve, and to show compassion and the will to help others.",
  "Love cannot remain by itself – it has no meaning. Love has to be put into action, and that action is service.",
  "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Every person can make a difference, and every person should try.",
  "Giving is not just about making a donation. It is about making a difference.",
  "You cannot do a kindness too soon, for you never know how soon it will be too late.",
  "I am only one, but I am one. I cannot do everything, but I can do something. And I will not let what I cannot do interfere with what I can do.",
  "Go into the world and do well. But more importantly, go into the world and do good.",
  "Service doesn’t have to be big and grandiose to be meaningful and make a difference.",
  "To handle yourself, use your head; to handle others, use your heart.",
  "When we give cheerfully and accept gratefully, everyone is blessed.",
  "Bring love wherever you go. Shine light wherever it's dark.",
  "Try to be a rainbow in someone's cloud.",
  "Give your hands to serve and your hearts to love.",
  "A kind gesture can reach a wound that only compassion can heal.",
  "The true measure of a man is how he treats someone who can do him no good.",
  "If you can’t feed a hundred people, then feed just one.",
  "Not all of us can do great things. But we can do small things with great love.",
  "Too often we underestimate the power of a touch, a smile, a kind word, a listening ear, an honest compliment, or the smallest act of caring, all of which have the potential to turn a life around.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.",
  "For it is in giving that we receive.",
  "The miracle is this: the more we share the more we have.",
  "There is nothing more beautiful than someone who goes out of their way to make life beautiful for others.",
  "Compassion is an action word with no boundaries.",
  "Caring has the gift of making the ordinary special.",
  "When you learn, teach. When you get, give.",
  "It is not how much we give but how much love we put into giving.",
  "The only way to have a friend is to be one.",
  "Kindness makes you the most beautiful person in the world, no matter what you look like.",
  "One person can make a difference, and everyone should try.",
  "Be the reason someone believes in the goodness of people.",
  "The struggle of today, is not altogether for today -- it is for a vast future.",
  "Great opportunities to help others seldom come, but small ones surround us every day.",
  "We make a life by what we give.",
  "Selfless giving is the art of living.",
  "There is no exercise better for the heart than reaching down and lifting people up.",
  "You play a part in the community you live in.",
  "Small acts, when multiplied by millions of people, can transform the world.",
  "Kindness is doing what you can, where you are, with what you have.",
  "Every sunrise is an invitation for us to arise and brighten someone's day.",
  "Be helpful. When you see a person without a smile, give them yours.",
  "Make someone's day by just being there.",
  "Your time is the most valuable gift you can give.",
  "Giving is the master key to success, in all applications of human life.",
  "A generous heart, kind speech, and a life of service and compassion are the things which renew humanity.",
  "Let us be the ones who say we do not accept that a child dies every three seconds simply because he does not have the drugs you and I have. Let us be the ones to say we are not satisfied that your place of birth determines your right to life. Let us be dissatisfied that we remain stymied by poverty and disease.",
  "Peace differs from true love because it can't be forced.",
  "A community is like a ship; everyone ought to be prepared to take the helm.",
  "The essence of life is to serve others and do good.",
  "Use your voice for kindness, your ears for compassion, your hands for charity, your mind for truth, and your heart for love.",
  "One distinct quality of a volunteer is they are willing to step up.",
  "Volunteering is the ultimate form of proactive citizenship.",
  "The world changes when we change.",
  "If you see a need, take the lead.",
  "Empathy is seeing with the eyes of another, listening with the ears of another and feeling with the heart of another.",
  "Strong people don't put others down... They lift them up.",
  "Be a reflection of what you'd like to receive. If you want love, give love. If you want truth, be truthful. If you want respect, give respect. What you give out will always return.",
  "Character is not made in a crisis; it is only exhibited.",
  "The road to success is paved with good intentions implemented.",
  "Don't wait for people to be friendly, show them how.",
  "Every charitable act is a stepping stone toward heaven.",
  "True charity is the desire to be useful to others with no thought of recompense.",
  "In a world where you can be anything, be kind.",
  "Do not let the behavior of others destroy your inner peace.",
  "Kindness begins with the understanding that we all struggle.",
  "Live simply so others may simply live.",
  "We are all angels with one wing. We can flip only if we embrace one another."
];
